name: flutter_map_radius_cluster_example
description: Example for Flutter Map Marker cluster

publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_map: ^4.0.0
  flutter_map_animations: ^0.3.0
  flutter_map_radius_cluster:
    path: ../
  kdbush: ^0.0.5
  latlong2: ^0.8.1

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
