name: flutter_map_radius_cluster
description: A marker clustering plugin for flutter_map which displays markers in a given radius.
version: 3.0.0

homepage: https://github.com/rorystephenson/flutter_map_radius_cluster

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  async: ^2.11.0
  flutter_map: ^4.0.0
  flutter_map_marker_popup: ^5.1.0
  latlong2: ^0.8.1
  provider: ^6.0.5
  supercluster: ^2.4.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
